// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// designM
arma::mat designM(arma::mat malpha, int model);
RcppExport SEXP GDINA_designM(SEXP malphaSEXP, SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type malpha(malphaSEXP);
    Rcpp::traits::input_parameter< int >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(designM(malpha, model));
    return rcpp_result_gen;
END_RCPP
}
// fitstats
Rcpp::List fitstats(arma::mat mX, arma::mat LCprob, arma::uvec attgroup);
RcppExport SEXP GDINA_fitstats(SEXP mXSEXP, SEXP LCprobSEXP, SEXP attgroupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type LCprob(LCprobSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type attgroup(attgroupSEXP);
    rcpp_result_gen = Rcpp::wrap(fitstats(mX, LCprob, attgroup));
    return rcpp_result_gen;
END_RCPP
}
// Lik
Rcpp::List Lik(arma::mat mP, arma::mat mX, arma::mat vlogPrior, arma::mat mIndmiss, arma::vec vgroup);
RcppExport SEXP GDINA_Lik(SEXP mPSEXP, SEXP mXSEXP, SEXP vlogPriorSEXP, SEXP mIndmissSEXP, SEXP vgroupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type mP(mPSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type vlogPrior(vlogPriorSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mIndmiss(mIndmissSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type vgroup(vgroupSEXP);
    rcpp_result_gen = Rcpp::wrap(Lik(mP, mX, vlogPrior, mIndmiss, vgroup));
    return rcpp_result_gen;
END_RCPP
}
// NgRg
List NgRg(arma::mat mlogPost, arma::mat mX, arma::mat mloc, arma::mat mIndmiss);
RcppExport SEXP GDINA_NgRg(SEXP mlogPostSEXP, SEXP mXSEXP, SEXP mlocSEXP, SEXP mIndmissSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type mlogPost(mlogPostSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mloc(mlocSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mIndmiss(mIndmissSEXP);
    rcpp_result_gen = Rcpp::wrap(NgRg(mlogPost, mX, mloc, mIndmiss));
    return rcpp_result_gen;
END_RCPP
}
// Rljs
arma::mat Rljs(arma::mat mlogPost, arma::mat mX, arma::vec vC);
RcppExport SEXP GDINA_Rljs(SEXP mlogPostSEXP, SEXP mXSEXP, SEXP vCSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type mlogPost(mlogPostSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type vC(vCSEXP);
    rcpp_result_gen = Rcpp::wrap(Rljs(mlogPost, mX, vC));
    return rcpp_result_gen;
END_RCPP
}
// scorefun
Rcpp::List scorefun(arma::mat mX, arma::mat mlogPost, arma::mat itmpar, arma::mat parloc, arma::vec model);
RcppExport SEXP GDINA_scorefun(SEXP mXSEXP, SEXP mlogPostSEXP, SEXP itmparSEXP, SEXP parlocSEXP, SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mlogPost(mlogPostSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type itmpar(itmparSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type parloc(parlocSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(scorefun(mX, mlogPost, itmpar, parloc, model));
    return rcpp_result_gen;
END_RCPP
}
// SE
Rcpp::List SE(arma::mat mX, arma::mat mlogPost, arma::mat itmpar, arma::mat parloc, arma::vec model, arma::mat mIndmiss, int SE_type);
RcppExport SEXP GDINA_SE(SEXP mXSEXP, SEXP mlogPostSEXP, SEXP itmparSEXP, SEXP parlocSEXP, SEXP modelSEXP, SEXP mIndmissSEXP, SEXP SE_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mlogPost(mlogPostSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type itmpar(itmparSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type parloc(parlocSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type model(modelSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mIndmiss(mIndmissSEXP);
    Rcpp::traits::input_parameter< int >::type SE_type(SE_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(SE(mX, mlogPost, itmpar, parloc, model, mIndmiss, SE_type));
    return rcpp_result_gen;
END_RCPP
}
// sequP
List sequP(arma::mat mloc, arma::mat mpar, arma::vec vC);
RcppExport SEXP GDINA_sequP(SEXP mlocSEXP, SEXP mparSEXP, SEXP vCSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type mloc(mlocSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mpar(mparSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type vC(vCSEXP);
    rcpp_result_gen = Rcpp::wrap(sequP(mloc, mpar, vC));
    return rcpp_result_gen;
END_RCPP
}
// uP
arma::mat uP(arma::mat mloc, arma::mat mpar);
RcppExport SEXP GDINA_uP(SEXP mlocSEXP, SEXP mparSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type mloc(mlocSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mpar(mparSEXP);
    rcpp_result_gen = Rcpp::wrap(uP(mloc, mpar));
    return rcpp_result_gen;
END_RCPP
}
// varsigma
arma::mat varsigma(arma::mat mloc, arma::mat mP, arma::vec vw);
RcppExport SEXP GDINA_varsigma(SEXP mlocSEXP, SEXP mPSEXP, SEXP vwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type mloc(mlocSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mP(mPSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type vw(vwSEXP);
    rcpp_result_gen = Rcpp::wrap(varsigma(mloc, mP, vw));
    return rcpp_result_gen;
END_RCPP
}
