# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aggregateCol <- function(mX, ind) {
    .Call('GDINA_aggregateCol', PACKAGE = 'GDINA', mX, ind)
}

designM <- function(malpha, model) {
    .Call('GDINA_designM', PACKAGE = 'GDINA', malpha, model)
}

fitstats <- function(mX, LCprob, attgroup) {
    .Call('GDINA_fitstats', PACKAGE = 'GDINA', mX, LCprob, attgroup)
}

Lik <- function(mP, mX, vlogPrior, vgroup) {
    .Call('GDINA_Lik', PACKAGE = 'GDINA', mP, mX, vlogPrior, vgroup)
}

NgRg <- function(mlogPost, mX, mloc) {
    .Call('GDINA_NgRg', PACKAGE = 'GDINA', mlogPost, mX, mloc)
}

Rljs <- function(mlogPost, mX, vC) {
    .Call('GDINA_Rljs', PACKAGE = 'GDINA', mlogPost, mX, vC)
}

scorefun <- function(mX, mlogPost, itmpar, parloc, model) {
    .Call('GDINA_scorefun', PACKAGE = 'GDINA', mX, mlogPost, itmpar, parloc, model)
}

sequP <- function(mloc, mpar, vC) {
    .Call('GDINA_sequP', PACKAGE = 'GDINA', mloc, mpar, vC)
}

uP <- function(mloc, mpar) {
    .Call('GDINA_uP', PACKAGE = 'GDINA', mloc, mpar)
}

varsigma <- function(mloc, mP, vw) {
    .Call('GDINA_varsigma', PACKAGE = 'GDINA', mloc, mP, vw)
}

